swagger: "2.0"
info:
  description: "This is an api documentation of drug sevice"
  version: "1.0.0"
  title: "Swagger drug service"
  contact:
    email: "penkobor@fel.cvut.cz"
tags:
- name: "drug-svc"
  description: "Everything about drug"
schemes:
- "http"
paths:
  /drug:
    get:
      tags:
      - "drug"
      summary: "gets all drugs in array"
      description: ""
      produces:
      - "application/json"
      responses:
        "200":
          description: "Valid input"
        "400":
          description: "Bad request"
  /drug/byId/{drugId}:
    get:
      tags:
      - "drug"
      summary: "Gets drug object by Id"
      operationId: "getDrugById"
      produces:
      - "application/json"
      parameters:
      - name: "drugId"
        in: "path"
        description: "Id of a drug that needs to be returned"
        required: true
        type: "string"
        default: ""
      responses:
        "200":
          description: "successful operation"
        "400":
          description: "Invalid status value"
  /drug/byName/{drugName}:
    get:
      tags:
      - "drug"
      summary: "Gets drug object by name"
      operationId: "getDrugByName"
      produces:
      - "application/json"
      parameters:
      - name: "drugName"
        in: "path"
        description: "Name of a drug that needs to be returned"
        required: true
        type: "string"
        default: ""
      responses:
        "200":
          description: "successful operation"
        "400":
          description: "Invalid status value"
  /drug/updateById/{id}/{availability}/{amount}:
    patch:
      tags:
      - "drug"
      summary: "updates drug by id" 
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
        default: ""
      - name: "availability"
        in: "path"
        required: true
        type: "boolean"
        default: ""
      - name: "amount"
        in: "path"
        required: true
        type: "string"
        default: ""
      responses:
        "200":
          description: "successful operation"
        "400":
          description: "Invalid status value"
  /drug/deleteById/{id}:
    post:
      tags:
      - "drug"
      summary: "delete drug by id"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
        default: ""
      responses:
        "200":
          description: "successful operation"
        "400":
          description: "Invalid status value"
  /drug/suggestPrescription/{illnessesId}:
    get:
      tags:
      - "drug"
      summary: "accepts illnessIds separated by comma (e.g /1,43,5) and returns array of drug ids"
      parameters:
      - name: "illnessesId"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "array of drug ids present in db"
        "400":
          description: "invalid status value"
definitions:
  drug:
    type: "object"
    properties:
      name:
        type: "string"
      available:
        type: "boolean"
      amount:
        type: "integer"
        format: "int32"
