version: '3'
services:
  drugs-svc:
    image: "drug-svc"
    build: .
    environment: 
      PORT: 5000
      EUREKA_PORT: 8761
      EUREKA_HOST: '172.19.0.2'
    command: "node server.js"
    ports:
      - "5000:5000"
    depends_on:
      - "mongo"
    networks: 
      - "nemocnice-network"
      - "mongo"
  mongo:
    image: "mongo"
    networks: 
      - "mongo"
networks: 
  mongo:
    driver: bridge
  nemocnice-network:
    external:
      name: nemocnice-network